### ISSUE TITLE
Ansible error on Ubuntu 20.04

### ISSUE THREAD

**Issue by toddingarfield** [ShubhamTatvamasi/kind-galaxy#1]
Hi, 

Looking to install Magma Orchestrator on local VM.   Ran across a couple of minor issues to get started but got this error at the end.   

Any suggestions on what to check are appreciated.  

BR,
Todd

TASK [metallb : Get Kind Cluster Node Info] *********************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Could not find imported module support code for ansiblemodule.  Looked for either AnsibleTurboModule.py or module.py"}

PLAY RECAP ******************************************************************************************************************************************
localhost                  : ok=29   changed=21   unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

```
Steps:
# apt-get install docker-ce docker-ce-cli containerd.io
# apt install ansible
# ansible-galaxy collection install shubhamtatvamasi.kind
// -U (upgrade part not supported) so I dropped it
# ansible-playbook /root/.ansible/collections/ansible_collections/shubhamtatvamasi/kind/deploy-kind.yml -K
```

**Comment by ShubhamTatvamasi** [comment]
Hi @toddingarfield, you are getting this error due to old Ansible version.

1. First remove old Ansible version:

```bash
sudo apt remove ansible
```

2. Then install the latest version:

```bash
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install ansible
```

**Comment by toddingarfield** [comment]
Thanks @ShubhamTatvamasi, that corrected the issue and the installation completed sucessfully.
